# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b48ed0bdef82d26a65a6a5141719791720ec01d32a39ae65cad6d656a6f760a339171b0afbb8f49d257378490a5561debccefb0f9c3a7a91a6d00a578e591b5

test:
  secret_key_base: fea1e6c41c9355894319c1e0f8ad5877ce025ca491aac32e527d57efc4dde3261757e31b0aea1379c4c5a79b01c18be5e35de31000200e4c4868b82e4eed95f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
